package model;
// Generated 20-ene-2020 16:49:57 by Hibernate Tools 4.3.1.Final

/**
 * Device generated by hbm2java
 */
public class Device implements java.io.Serializable {

	private int deviceId;
	private String name;

	public Device() {
	}

	public Device(int deviceId, String name) {
		this.deviceId = deviceId;
		this.name = name;
	}

	public int getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(int deviceId) {
		this.deviceId = deviceId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
